### ISSUE TITLE
plz insert your google.json

### ISSUE THREAD

**Issue by mynameismhmd** [edilsonmatola/habitual-ecommerce-app-getx#4]

**Comment by edilsonmatola** [comment]
Hi @mynameismhmd, Thank you for bringing this issue to my attention.

Unfortunately the application is still under development, specifically in the User Interface phase. 

**There is no google.json file** as the business logic has not yet been implemented and the app will not use firebase for the backend. For more details of the project, read [this article](https://medium.com/@edilsonmatola/habitual-the-flutter-ecommerce-app-39ce126a3b2b) that I wrote for a better understanding of the overall purpose of this app.

If you have any further questions or concerns, please don't hesitate to reach out. 

Best regards,

Edilson Matola
